# Generated by Django 6.0.5 on 2026-05-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=20)),
                ('restaurant_name', models.CharField(max_length=20)),
                ('order_status', models.CharField(max_length=20)),
                ('food_name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
